

 

 # Site settings
title: Ahmed Munawar
email: your-email@domain.com
url: "https://engr-ahmad-munawar.github.io"
baseurl: ""
description: "Computer Engineering Student | Exploring Systems & Code."
keywords: "Engineering, C++, SQL, Development, Portfolio"
skills: "Computer Engineering Student - Tech Explorer - Programmer"
meta_author: Ahmed Munawar

# Google webmaster tools
google_verify:

# Contact form settings
contact: static

# Color settings
color:
  primary: 18bc9c 
  primary-rgb: "24,288,156"
  secondary: 2c3e50 
  secondary-dark: 233140 

# Footer settings
footer:
  copyright: Ahmed Munawar
  location: Location
  social: Around the Web
  credits: Credits

# Social networks (Update these with your actual links)
social:
  - title: github
    url: https://github.com/engr-ahmad-munawar
  - title: linkedin
    url: # Add your LinkedIn URL here
  - title: stack-overflow
    url: # Add your Stack Overflow URL here

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# For posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
